### ISSUE TITLE
Refactoring of UserRepository

### ISSUE THREAD

**Issue by dawciobiel** [Simple-as-Coding/tutoring-platform#19]
Klasa:
https://github.com/Simple-as-Coding/tutoring-platform/blob/main/src/main/java/pl/simpleascoding/tutoringplatform/repository/**UserRepository**.java

L:9     
**jest:**
findByUsername()

**powinno być:**  
findByUser**N**ame()

**Comment by Eukon05** [comment]
Dlaczego tak? Pole w klasie User nazywa się `username`, a `findByUsername()` to nazwa, którą podpowiedziało mi IDEA
![image](https://user-images.githubusercontent.com/43497104/176533713-d07189c6-a1e7-4b07-afa5-bbb36ea89c6f.png)

**Comment by MateuszCiapala** [comment]
resolved
